#pragma once

#include <emlite/emlite.h>
#include <jsbind/jsbind.h>
#include "Node.h"
#include "enums.h"

class DOMImplementation;
class DocumentType;
class Element;
class HTMLCollection;
class DocumentFragment;
class Text;
class CDATASection;
class Comment;
class ProcessingInstruction;
class Attr;
class Event;
class Range;
class NodeIterator;
class TreeWalker;
class SVGSVGElement;
class NamedFlowMap;
class ViewTransition;
class CaretPosition;
class CaretPositionFromPointOptions;
class FontMetrics;
class StylePropertyMapReadOnly;
class Document;
class Location;
class HTMLElement;
class HTMLHeadElement;
class NodeList;
class HTMLAllCollection;
class PermissionsPolicy;
class FragmentDirective;
class Selection;
class DocumentTimeline;
class FontFaceSet;
class DOMQuad;
class BoxQuadOptions;
class DOMQuadInit;
class ConvertCoordinateOptions;
class DOMRectReadOnly;
class DOMPoint;
class Animation;
class XPathExpression;
class XPathResult;
class ShadowRoot;
class DOMPointInit;
class DOMQuadInit;
