#pragma once

#include <emlite/emlite.h>
#include <jsbind/jsbind.h>
#include "EventTarget.h"
#include "enums.h"

class GPUSupportedFeatures;
class GPUSupportedLimits;
class GPUAdapterInfo;
class GPUQueue;
class GPUBuffer;
class GPUBufferDescriptor;
class GPUTexture;
class GPUTextureDescriptor;
class GPUSampler;
class GPUSamplerDescriptor;
class GPUExternalTexture;
class GPUExternalTextureDescriptor;
class GPUBindGroupLayout;
class GPUBindGroupLayoutDescriptor;
class GPUPipelineLayout;
class GPUPipelineLayoutDescriptor;
class GPUBindGroup;
class GPUBindGroupDescriptor;
class GPUShaderModule;
class GPUShaderModuleDescriptor;
class GPUComputePipeline;
class GPUComputePipelineDescriptor;
class GPURenderPipeline;
class GPURenderPipelineDescriptor;
class GPUCommandEncoder;
class GPUCommandEncoderDescriptor;
class GPURenderBundleEncoder;
class GPURenderBundleEncoderDescriptor;
class GPUQuerySet;
class GPUQuerySetDescriptor;
class GPUDeviceLostInfo;
class GPUError;
