#pragma once

#include <emlite/emlite.h>
#include <jsbind/jsbind.h>
#include "EventTarget.h"
#include "enums.h"

typedef struct wb_GPUSupportedFeatures wb_GPUSupportedFeatures;
typedef struct wb_GPUSupportedLimits wb_GPUSupportedLimits;
typedef struct wb_GPUAdapterInfo wb_GPUAdapterInfo;
typedef struct wb_GPUQueue wb_GPUQueue;
typedef struct wb_GPUBuffer wb_GPUBuffer;
typedef struct wb_GPUBufferDescriptor wb_GPUBufferDescriptor;
typedef struct wb_GPUTexture wb_GPUTexture;
typedef struct wb_GPUTextureDescriptor wb_GPUTextureDescriptor;
typedef struct wb_GPUSampler wb_GPUSampler;
typedef struct wb_GPUSamplerDescriptor wb_GPUSamplerDescriptor;
typedef struct wb_GPUExternalTexture wb_GPUExternalTexture;
typedef struct wb_GPUExternalTextureDescriptor wb_GPUExternalTextureDescriptor;
typedef struct wb_GPUBindGroupLayout wb_GPUBindGroupLayout;
typedef struct wb_GPUBindGroupLayoutDescriptor wb_GPUBindGroupLayoutDescriptor;
typedef struct wb_GPUPipelineLayout wb_GPUPipelineLayout;
typedef struct wb_GPUPipelineLayoutDescriptor wb_GPUPipelineLayoutDescriptor;
typedef struct wb_GPUBindGroup wb_GPUBindGroup;
typedef struct wb_GPUBindGroupDescriptor wb_GPUBindGroupDescriptor;
typedef struct wb_GPUShaderModule wb_GPUShaderModule;
typedef struct wb_GPUShaderModuleDescriptor wb_GPUShaderModuleDescriptor;
typedef struct wb_GPUComputePipeline wb_GPUComputePipeline;
typedef struct wb_GPUComputePipelineDescriptor wb_GPUComputePipelineDescriptor;
typedef struct wb_GPURenderPipeline wb_GPURenderPipeline;
typedef struct wb_GPURenderPipelineDescriptor wb_GPURenderPipelineDescriptor;
typedef struct wb_GPUCommandEncoder wb_GPUCommandEncoder;
typedef struct wb_GPUCommandEncoderDescriptor wb_GPUCommandEncoderDescriptor;
typedef struct wb_GPURenderBundleEncoder wb_GPURenderBundleEncoder;
typedef struct wb_GPURenderBundleEncoderDescriptor wb_GPURenderBundleEncoderDescriptor;
typedef struct wb_GPUQuerySet wb_GPUQuerySet;
typedef struct wb_GPUQuerySetDescriptor wb_GPUQuerySetDescriptor;
typedef struct wb_GPUDeviceLostInfo wb_GPUDeviceLostInfo;
typedef struct wb_GPUError wb_GPUError;
