#pragma once

#include <emlite/emlite.h>
#include <jsbind/jsbind.h>
#include "MLContext.h"
#include "enums.h"

class MLOperand;
class MLTensor;
class MLGraph;
class MLArgMinMaxOptions;
class MLBatchNormalizationOptions;
class MLOperatorOptions;
class MLClampOptions;
class MLConv2dOptions;
class MLConvTranspose2dOptions;
class MLCumulativeSumOptions;
class MLEluOptions;
class MLGatherOptions;
class MLGemmOptions;
class MLGruOptions;
class MLGruCellOptions;
class MLHardSigmoidOptions;
class MLInstanceNormalizationOptions;
class MLLayerNormalizationOptions;
class MLLeakyReluOptions;
class MLLinearOptions;
class MLLstmOptions;
class MLLstmCellOptions;
class MLPadOptions;
class MLPool2dOptions;
class MLReduceOptions;
class MLResample2dOptions;
class MLReverseOptions;
class MLScatterOptions;
class MLSliceOptions;
class MLSplitOptions;
class MLTransposeOptions;
class MLTriangularOptions;
