#pragma once

#include <emlite/emlite.h>
#include <jsbind/jsbind.h>
#include "Credential.h"
#include "enums.h"

typedef struct wb_AuthenticatorResponse wb_AuthenticatorResponse;
typedef struct wb_AuthenticationExtensionsClientOutputs wb_AuthenticationExtensionsClientOutputs;
typedef struct wb_PublicKeyCredentialCreationOptions wb_PublicKeyCredentialCreationOptions;
typedef struct wb_PublicKeyCredentialCreationOptionsJSON wb_PublicKeyCredentialCreationOptionsJSON;
typedef struct wb_PublicKeyCredentialRequestOptions wb_PublicKeyCredentialRequestOptions;
typedef struct wb_PublicKeyCredentialRequestOptionsJSON wb_PublicKeyCredentialRequestOptionsJSON;
typedef struct wb_UnknownCredentialOptions wb_UnknownCredentialOptions;
typedef struct wb_AllAcceptedCredentialsOptions wb_AllAcceptedCredentialsOptions;
typedef struct wb_CurrentUserDetailsOptions wb_CurrentUserDetailsOptions;
