#pragma once

#include <emlite/emlite.h>
#include <jsbind/jsbind.h>
#include "EventTarget.h"
#include "window.h"
#include "enums.h"

class Document;
class Location;
class History;
class Navigation;
class CustomElementRegistry;
class BarProp;
class Element;
class Navigator;
class WindowPostMessageOptions;
class CookieStore;
class Viewport;
class MediaQueryList;
class Screen;
class VisualViewport;
class CSSStyleDeclaration;
class DigitalGoodsService;
class DocumentPictureInPicture;
class Fence;
class FileSystemFileHandle;
class OpenFilePickerOptions;
class SaveFilePickerOptions;
class FileSystemDirectoryHandle;
class DirectoryPickerOptions;
class External;
class FontData;
class QueryOptions;
class PortalHost;
class IdleRequestOptions;
class Selection;
class SharedStorage;
class SpeechSynthesis;
class LaunchQueue;
class ScreenDetails;
class Crypto;
class Storage;
